name: flutter_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  rflutter_alert: ^2.0.4
  get_it: ^8.2.0
  watch_it: ^1.7.0
  jwt_decode: ^0.3.1
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  provider: ^6.0.0
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  skeletons: ^0.0.3
  carousel_slider: ^5.1.1
  get: ^4.6.5
  country_code_picker: ^3.0.0
  image_picker: ^1.2.0
  url_launcher: ^6.1.4
  share_plus: ^11.1.0
  jiffy: ^6.2.1
  connectivity_plus: ^6.1.5
  flutter_multi_formatter: ^2.5.7
  geocoding: ^4.0.0
  google_nav_bar: ^5.0.6
  indexed: ^0.0.8
  flutter_widget_from_html_core: ^0.17.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.1.2
  loader_overlay: ^5.0.0
  font_awesome_flutter: ^10.10.0
  ionicons: ^0.2.2
  feather_icons: ^1.2.0
  image_cropper: ^9.1.0
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html: ^0.17.1
  fwfh_webview: ^0.15.5
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.1
  webview_flutter_wkwebview: ^3.19.0
  html: ^0.15.4
  flutter_launcher_icons: ^0.14.4
  file_picker: ^10.3.2
  in_app_purchase: ^3.0.7
  rate_limiter: ^1.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.1
  app_badge_plus: ^1.2.3
  flutter_vector_icons: ^2.0.0
  easy_localization: ^3.0.3
  auth_buttons: ^3.0.3
  fwfh_just_audio: ^0.17.0
  syncfusion_flutter_pdfviewer: ^30.2.7
  flutter_stripe: ^12.0.2
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.4
  email_validator: ^3.0.0
  youtube_player_flutter: ^9.1.2
  vimeo_video_player: ^1.0.1
  flutter_inappwebview: ^6.2.0-beta.2

dependency_overrides:
  flutter_inappwebview: ^6.2.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mobx_codegen: ^2.2.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/icon/
    - assets/images/icon-tab/

  fonts:
    - family: SnigletBold
      fonts:
        - asset: assets/fonts/Sniglet-ExtraBold.ttf

    - family: Sniglet
      fonts:
        - asset: assets/fonts/Sniglet-Regular.ttf

    - family: SnigletExtraBold
      fonts:
        - asset: assets/fonts/Sniglet ExtraBold 800.ttf

    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: poppins-extraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf